name: Build AdbLib Jar

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Compile Java Files and Create Jar
      run: |
        mkdir -p build/classes
        # Mencari dan mengkompilasi semua file .java di dalam folder src
        javac -d build/classes $(find src -name "*.java")
        # Membungkusnya menjadi adblib.jar
        jar cvf adblib.jar -C build/classes .
        
    - name: Upload Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: adblib-jar-ready
        path: adblib.jar
